#!/bin/bash

# HTML Template
function createHTML() {
  cat << EOT >> index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>$1</title>
  <link rel="stylesheet" href="css/styles.css">
</head>
<body>
  <h1>
    Hello World.
  </h1>
</body>
</html>
EOT
}

# CSS Template
function CreateCSS() {
  cat << EOT >> styles.css
body {
  margin: 0;
  padding: 0;
  font-family: 'Verdana', sans-serif;
}
EOT
}

# Bootstrap Template
function bootstrap() {
  cat << EOT >> index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>$1</title>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="css/styles.css">
</head>
<body>
  <h1>
    Hello World.
  </h1>
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" ></script>
</body>
</html>
EOT
}

OPTION_FLAG=0
TITLE=$1

if [[ $1 =~ ^[a-z|A-Z|0-9] ]]; then
  if [ -d "$1" ]; then
    echo "'$1' has already exsist"
  else
    mkdir $1 && cd $_ && createHTML $1 &&
    mkdir css && touch styles.css && CreateCSS && mv styles.css css && OPTION_FLAG=1
  fi
else
  echo "usage: gen app_name [-h new HTML name][-b bootstrap template][-c new CSS name][-j javascript file]"
fi

if [ $OPTION_FLAG -eq 1 ]; then
  while [ "$1" ]
  do
    while getopts "h:c:jb" op
    do
      case $op in
        h)
          HTML_NAME="$OPTARG"
          mv index.html "$HTML_NAME.html"
          ;;
        b)
          rm *.html && bootstrap $TITLE
          ;;
        c)
          CSS_NAME="$OPTARG"
          mv ./css/styles.css ./css/"$CSS_NAME.css"
          ;;
        j)
          mkdir js && cd $_ && touch main.js
          ;;
        *)
          exit 1
          ;;
      esac
    done
    shift
  done
fi